//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marley.Currency.WindowsService.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetList", ReplyAction="http://tempuri.org/IService/GetListResponse")]
        Marley.Currency.Domain.DataEntities.Stock[] GetList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetList", ReplyAction="http://tempuri.org/IService/GetListResponse")]
        System.Threading.Tasks.Task<Marley.Currency.Domain.DataEntities.Stock[]> GetListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateStocks", ReplyAction="http://tempuri.org/IService/UpdateStocksResponse")]
        string UpdateStocks(Marley.Currency.Domain.DataEntities.Stock[] stockList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateStocks", ReplyAction="http://tempuri.org/IService/UpdateStocksResponse")]
        System.Threading.Tasks.Task<string> UpdateStocksAsync(Marley.Currency.Domain.DataEntities.Stock[] stockList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Marley.Currency.WindowsService.ServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Marley.Currency.WindowsService.ServiceReference.IService>, Marley.Currency.WindowsService.ServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Marley.Currency.Domain.DataEntities.Stock[] GetList() {
            return base.Channel.GetList();
        }
        
        public System.Threading.Tasks.Task<Marley.Currency.Domain.DataEntities.Stock[]> GetListAsync() {
            return base.Channel.GetListAsync();
        }
        
        public string UpdateStocks(Marley.Currency.Domain.DataEntities.Stock[] stockList) {
            return base.Channel.UpdateStocks(stockList);
        }
        
        public System.Threading.Tasks.Task<string> UpdateStocksAsync(Marley.Currency.Domain.DataEntities.Stock[] stockList) {
            return base.Channel.UpdateStocksAsync(stockList);
        }
    }
}
